### PR TITLE
Updated dependency list

### PR DESCRIPTION
**Pull request by azuwey**
Updated dependency list with K&R code style.

### CODE REVIEW

**Comment by pantor** [comment]
I prefer that the user includes the json dependency himself. This way he knows json exists and should be used for data handling.

**Comment by craigpepper** [comment]
Our projects use a code auto formatter that places #includes in alphabetical order.  The auto formatter breaks the dependency order since it moves `#include <json.hpp>` to the line after `#include <inja.hpp>`.  I have to insert a blank line or comment between the inja and json #includes to stop the reordering, which feels hacky.

I would prefer if inja included json so I did not have this inconvenience.

**Comment by azuwey** [comment]
@craigpepper I have the same issue, this is why I made this changes and I think this should be the prefered method to include all of the dependencies. Also @pantor if the user does not include the JSON dependecy it should throw an error if he try to use without include it, and I think the compiler is smart enough to tell the user, it have to include the JSON dependecy, because it won't work without it.

**Comment by pantor** [comment]
Thanks, that really makes sense. I've updated inja with the latest commit, so I'll close this PR now.

**Pull request closed without merging**
