### PR TITLE
Add alternative syntax for new line handling after statements.  Add variables index, index1, is_first and is_last to object loops

### PR DESCRIPTION
**Pull request by craigpepper**
In response to Issue #49, add the alternative synatx `{% ... -%}` for statements.
The `-%}` must appear at the end of a line, in which case the new line will be
suppressed in the generated result.

Note that this does not replicate the complete whitespace handling functionality of Jinja, it just provides a simple way to manage newline handling after statements.

### CODE REVIEW

**Comment by craigpepper** [comment]
I had intended to make a new PR for the variables in object loops update, but pushing to master on my fork updated this existing PR.  Hopefully you'll find both changes acceptable.

**Comment by Edwinem** [comment]
Craigpepper,
Thanks a lot, the new {% ..... -%} notation for the most part seems to work well. 

However, there seems to be some bug which causes the indenting on the next line to mess up

Currently this is extracted from one of my files. I will try and get a minimal example up and running over the weekend.

Is subsection of a large code base
~~~
--------------------------------Start block --------------------------------------------------------------------------------------------
				{% if var.can_serialize and not var.is_ptr -%}
					{% if var.is_pod -%}
        //SOMETHING HERE
	size += Pack_{{var.type}}(&cast_ptr->{{var.name}}, buffer + size);
					{% endif %}
				{% endif %}
--------------------------------End block --------------------------------------------------------------------------------------------
~~~

Becomes this.
~~~
--------------------------------Start block --------------------------------------------------------------------------------------------
															    //SOMETHING HERE
	size += Pack_double(&cast_ptr->max_thrust, buffer + size);
--------------------------------End block --------------------------------------------------------------------------------------------
~~~

The indenting of the //SOMETHING HERE code is messed up.

**Comment by craigpepper** [comment]
Thanks, glad you like the update.

I think the issue you're seeing is that the leading spaces in commands before the //SOMETHING HERE line are being preserved in the output.  The `-%}` eats the newlines after the commands, so you're left with a long string on spaces on a single line.

To illustrate:

    --------------------------------Start block ----------------------------------------
    1111111111111111{% if var.can_serialize and not var.is_ptr -%}
    222222222222222222222222{% if var.is_pod -%}
    33333333//SOMETHING HERE
            size += Pack_{{var.type}}(&cast_ptr->{{var.name}}, buffer + size);
                            {% endif %}
                    {% endif %}
    --------------------------------End block ------------------------------------------

becomes
   
    --------------------------------Start block ----------------------------------------
    111111111111111122222222222222222222222233333333//SOMETHING HERE
            size += Pack_{{var.type}}(&cast_ptr->{{var.name}}, buffer + size);
                            {% endif %}
                    {% endif %}
    --------------------------------End block ------------------------------------------

The `-%}` syntax eats whitespace up to an including the newline after the command.  It should be easy enough to add an additional syntax `{%-` which eats whitespace from the start of the line.  I'll make this change and push it up later today.

**Comment by craigpepper** [comment]
The latest commits adds the `{%-` syntax, which consumes whitespace from the the start of the line to the `{%-`.  It also fixes issue #35, which concerned strange space handling in line commands.

The following templates all now produce identical output:

```
{% for i in var -%}
    i
{% endfor %}
```
```
        {%- for i in var -%}
    i
        {%- endfor %}
```
```
## for i in var
    i
## endfor
```

**Comment by craigpepper** [comment]
The most recent commit fails some tests under Linux, although the same tests pass in Windows.  I have spent some time attempting to work a solution without success so far,  In the process I've learned a lot more about regex than is probably good for me.  However, it does seem that C++17 regex will have a feature (std::regex::multiline) that will help with the issues encountered.

For now I'm going to close this PR, and open two new ones - one for the variables in object loops, and another for the newline handling update (before I tried to get too tricky)

**Pull request closed without merging**
