### PR TITLE
Execute statement

### PR DESCRIPTION
**Pull request by DeiRex75**
Similar to the set statement i was in need of a execute statement.

The execute statement executes a given expression but doesn't render it.
This helps to call functions that just want to be executed.
For example, adding a debug function that dumps the object but doesn't change the result.

I would love to have this or something similar added.

```
{% execute a_dump_function(data) -%} Something was dumped.
```
Would just result in "Something was dumped."

This use case is just an example. Not a good one to be honest.
The issue is that currently no option is available to just call a function without rendering something.
Using an expression and returning "" doesn't allow for whitespace control.

### CODE REVIEW

**Comment by pantor** [comment]
Thanks for your PR!

I think I would integrate your execution statement within the callback approach. I've added a void callback to the master branch, maybe you can have a look at this. I've added an example to the Readme as well.

**Comment by DeiRex75** [comment]
Overall love your approach.
But the major part i wanted from this was the whitespace control.


One little thing i miss
 is the whitespace control, specialy for '\n'.

I generate from template to files.
So if I use void_callbacks to log, it will result in an empty line. 
Well, only if i want to 

``
{{ log("A") }}\n
Lorem ipsum
``

>  \n
> Lorem ipsum

**Comment by DeiRex75** [comment]
Overall love your approach.
But the major part i wanted from this was the whitespace control.

I use template files.
Therefore i would have to write:
>{{ log("A") }}{{ log("B") }}{{ log("C") }}Lorem Ipsum

To process the logging and write the text without additional lines.
What i would like to write is:
>{{ log("A") }}  
>{{ log("B") }}  
>{{ log("C") }}  
>Lorem Ipsum

to result just in "Lorem Ipsum".
Whitespace control is only possible for statements.
Therefore another possibility to result not in multiple lines would be to add a statement with control at the end of each logging line.

Another idea could be to remove the newline after an expression if "-}" or "-}}" is used to close it.
This would have to explicit and not be affected by rstrip /lstrip.

**Comment by pantor** [comment]
Ah, I see.

I think we should follow jinja2 here and add whitespace control to variables as well.

**Comment by DeiRex75** [comment]
Thanks for the information again.
If it is in jinja2 i would love to see this implemented as well.
I will close this for now.

**Pull request closed without merging**
